site_name: Yiduo Wang

# theme:
#   name: material
#   # logo: './images/favicon.png'
#   # favicon: './images/favicon.png'
#   # menu: './images/favicon.png'

#   palette: 
#     scheme: default
#     accent: cyan
#     primary: cyan

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

  # features:
    # - header.autohide
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections

nav:
  - HOME: 'index.md'
  - X (Twitter): 'https://x.com/yiduo_wang_32'
  - GitHub: 'https://github.com/yiduo-wang-32'

extra_css:
  - css/main.css

# extra_javascript:
#   - assets/script.js

markdown_extensions:
  - attr_list
  - md_in_html

# plugins: []  # remove search bar
